import 'package:flutter/material.dart';

class PrivacyDetail extends StatelessWidget {
  const PrivacyDetail({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.green[300],
        title: Text("Health"),
      ),
      body: SingleChildScrollView(
        child: Container(
          child: Text("SMART-TIME PRO respects and protects user information and treats it with a high degree of responsibility and care. When you use the services provided by SMART-TIME PRO, we collect, process and disclose your information in accordance with this Privacy Policy. We want to give you a clear picture of how we handle your information through this Privacy Policy, so we recommend that you read this Privacy Policy in its entirety to help you understand how to maintain your privacy."
              "\n"
              "\n"
              "If you have any questions, comments or suggestions, you can contact us through the official website."
              "\n"
              "\n"
              "This policy will help you understand the following:"
              "\n"
              "\n"
             " 1. Scope of application"
              "\n"
              "\n"
             " 2. Collection and use of user information"
              "\n"
              "\n"
              "3. Sharing, transfer, and public disclosure of user information"
              "\n"
              "\n"
              "4. User motion data and public information"
              "\n"
              "\n"
              "5. Management of user information"
              "\n"
              "\n"
              "6. User Information Security"
              "\n"
              "\n"
              "7. Our policy towards children"
              "\n"
              "\n"
              "8. Claims about app permission usage"
              "\n"
              "\n"
              "9. The Updating of Privacy Policy"
              "\n"
              "\n"
              "10. How to contact us"
              "\n"
              "\n"
              "1. Scope of application"
              "\n"
              "\n"
              "1.1 This Privacy Policy applies to all services provided by SMART-TIME PRO. Services include providing you with web browsing and technical services provided to you through the SMART-TIME PRO website."
              "\n"
              "\n"
              "1.2 This Privacy Policy also applies to your use of SMART-TIME PRO applications, and the personal registration information required by the app when registering an app account includes, but is not limited to, your nickname, age, country, profile picture, height, gender, weight, unit of measurement used, etc. Application synchronized Bluetooth device data when using the app, including but not limited to your movement steps, heart rate data, sleep data, motion recording data, and location data generated during some exercises."
              "\n"
              "\n"
              "1.3 The user's personal data obtained by the App through legal means from business partners."
              "\n"
              "\n"
              "2. Collection and use of user information"
              "\n"
              "\n"
              "2.1 Help you to be our user"
              "\n"
              "\n"
              "2.1.1 When you create an account on the SMART-TIME PRO app, you must provide us with any entry for your email, mobile phone number, third-party login information as the key content of your login, and if you log in with your email or mobile phone number, we will send you a verification code for verification, as well as a verification of your login password. Your submitted email or mobile phone number is used to receive a verification code when you register, log in, bind your account, retrieve your password, and as one of the contact details you specify with the SMART-TIME PRO to receive relevant business notifications (e.g. health reports, service changes, etc.).If you use a third login, such as Google and Facebook, we will apply to the corresponding third-party platform for authorization to obtain your nickname and profile picture with your consent in order to authenticate you.The content of your data that we obtain from third parties depends on the settings, permissions and privacy policies controlled by the third party, and you should always take care to check the privacy settings and notifications in these third-party services to understand the data that may be disclosed to us or shared with our services. If you have security concerns, we recommend that you use your email to register and log in."
              "\n"
              "\n"
              "2.1.2 After you register for your SMART-TIME PRO account, you can continue to fill in your information in the next process, including but not limited to your nickname, age, profile picture, height, gender, weight, unit of measure used, etc."
              "\n"
              "\n"
              "2.2 Provide you with technical services"
              "\n"
              "\n"
              "2.2.1 In the course of your use, you can contact our sales staff at any time or through the APP's built-in feedback feature, you can give us feedback on your difficulties or doubts, while filling in the email that can contact you, we will contact you in a timely manner to provide support and services."
              "\n"
              "\n"
              "The information we collect during your use of the SMART-TIME PRO App is:"
              "\n"
              "\n"
          "2.2.2 Device Information: We will receive and record information about the device you are using (e.g. hardware and software feature information such as device model, operating system version, etc.) and use cookies to ensure the safe use of your data, in accordance with the specific permissions you grant in the installation and use of the Software."
              "\n"
              "\n"
          " 2.2.3 User Health Data: When you use our client side to sync data with the Bluetooth devices we sell, we automatically sync your movement steps, heart rate data, sleep data, motion recording data, and location data generated during some exercises under your account system"
              "\n"
              "\n"
          "2.2.4 Please note that individual device information, user health data, etc. are information that does not identify a particular natural person.If we combine such non-personal information with other information to identify or combine it with personal information, such non-personal information will be treated as personal information during the combined period of use and will be treated as anonymous and unidentified, unless authorized by you or otherwise provided by law and regulation."
              "\n"
              "\n"
          "2.2.5 User account support information: Based on the user's consulting records, question feedback records, and processing of user feedback (such as communications or call logs) based on your use of the Ali SMART-TIME PRO service or product, SMART-TIME PRO will record, analyze this information to respond more promptly to your help request, and use it to improve the Service."
              "\n"
              "\n"
          "2.3 We use the user information you submit and collect for the following purposes:"
              "\n"
              "\n"
          "2.3.1 In order to provide services to you (e.g. height, weight, age, is a prerequisite for continued access to services);"
              "\n"
              "\n"
          " 2.3.2 To maintain and improve the Services (e.g., the mobile phone number or mailbox you submit for the verification code, etc., to register, log in, or receive business notifications and communicate for business);"
              "\n"
              "\n"
          " 2.3.3 Under the premise of laws and regulations, to promote and introduce products to you;"
              "\n"
              "\n"
          " 2.3.4 To improve the security of your use of services provided by us and our affiliates and partners, to protect your or other users or the public from infringement, and to better protect against security risks such as phishing websites, fraud, network vulnerabilities, computer viruses, cyber attacks, and cyber intrusions. To more accurately identify violations of laws and regulations or SMART-TIME PRO related agreements and rules, we may use your user information, integrate device information, information about blogs, and information shared by our affiliates and partners to determine your account risk, authentication, detection and prevention of security incidents, and to document the necessary records as necessary in accordance with the law audit, analysis and disposal measures;"
              "\n"
              "\n"
          " 2.3.5 Other uses with your permission"
              "\n"
              "\n"
          "3. Sharing, transfer, and public disclosure of user information"
              "\n"
              "\n"
          "3.1 Sharing"
              "\n"
              "\n"
          " We do not share your user information with other organizations and individuals, except in the following cases:"
              "\n"
              "\n"
          " 3.1.1 Share with explicit consent: we will share your user information with other parties with your express consent;"
              "\n"
              "\n"
          "3.1.2 Sharing in legal circumstances: We may share your user information with the outside world in accordance with the provisions of laws and regulations, litigation, arbitration settlement needs, or in accordance with the requirements of the administrative and judicial authorities in accordance with the law;"
              "\n"
              "\n"
          "3.1.3 In order to assist with your feedback, in some cases only by sharing your user information can deal with your problems, such as when you use your mobile phone number to register your account or retrieve your password, you cannot receive the verification code information, we need to provide your mobile phone number to the SMS carrier we access, for them to query a transcript sent to your specific verification code to confirm the issue."
              "\n"
              "\n"
              "3.1.4 Share with authorized partners"
              "\n"
              "\n"
              "We may entrust trusted partners with the services, so we may share some of your user information with partners to provide better customer service and optimize the user experience.We will only share your user information for lawful, legitimate, necessary, specific, and explicit purposes, and only the user information necessary to provide the Services.Our partners do not have the right to use the shared user information for any other purpose."
              "\n"
              "\n"
              "Currently, our authorized partners include the following types: authorized distributors, service providers, and other partners.We send information to authorized distributors, service providers, and other partners who support our business, including providing basic technical services, consulting, analytic, and other professional services."
              "\n"
              "\n"
              "We may sign strict confidentiality agreements and information protection agreements with companies, organizations, and individuals with which we share user information, requiring them to process user information in accordance with our instructions, this privacy policy, and any other relevant confidentiality and security measures."
              "\n"
              "\n"
          "3.2 Transfer"
              "\n"
              "\n"
          "We will not transfer your user information to any company, organization, or individual, except in the following cases:"
              "\n"
              "\n"
          "3.2.1 Transfer with express consent: we will transfer your user information to other parties with your express consent;"
              "\n"
              "\n"
          "3.2.2 In the event of a merger, acquisition or liquidation of SMART-TIME PRO and other legal subjects, or other circumstances involving a merger, acquisition or liquidation, we will require new companies and organizations that hold your user information to remain subject to this policy, or we will require the company, Organizations and individuals re-request your authorization."
              "\n"
              "\n"
          "3.3 Public disclosure"
              "\n"
              "\n"
          "We will only publicly disclose your user information in the following case:"
              "\n"
              "\n"
              " With your express consent or based on your unsolicited choice, we may publicly disclose your user information;"
              "\n"
              "\n"
              " 3.4 Exceptions to obtain prior authorization for the sharing, transfer, and public disclosure of user information."
              "\n"
              "\n"
              " Sharing, transferring, and publicly disclosing your user information does not require your prior authorization to consent to:"
              "\n"
              "\n"
              "3.4.1 Related to national security, national defense security;"
              "\n"
              "\n"
          "3.4.2 Related to public safety, public health and major public interests;"
              "\n"
              "\n"
          " 3.4.3 Related to the investigation of crimes, prosecution, trial and enforcement of sentences;"
              "\n"
              "\n"
          "3.4.4 For the sake of safeguarding your or other personal life, property and other important legal rights and interests but it is difficult to obtain your own consent;"
              "\n"
              "\n"
              "3.4.5 Personal information that you disclose to the public on your own;"
              "\n"
              "\n"
              "3.4.6 Collecting personal information from information that is legally publicly disclosed, such as legitimate news reporting, government information disclosure, etc."
              "\n"
              "\n"
              "4. User motion data and public information"
              "\n"
              "\n"
          "Unlike your user information, the SMART-TIME PRO will handle user motion data and public information as follows:"
              "\n"
              "\n"
          " 4.1 User motion data "
              "\n"
              "\n"
          " 4.1.1 All data generated by the devices you purchase through SMART-TIME PRO or authorized distributors is your user motion data, and you have full ownership of your user motion data.As a service provider, SMART-TIME PRO will only process your motion data based on scientific, legal health algorithms and will only display motion data records and data processing results to you, without any unauthorized use or disclosure of your business data, except as required by consensus or enforcement of clear laws and regulations with you."
              "\n"
              "\n"
          "4.1.2 When you allow us to collect accurate location information, we use that information to provide and improve the functionality of the service, such as recording where exercise occurs and drawing your movement course during exercise."
              "\n"
             "\n"
          "4.1.3 We use your information to correct some data, such as using information, like your height, weight, gender, age, etc., to improve the accuracy of calculating your daily exercise data and activity statistics, common data have measured and calories; based on your sleep data, we may infer your sleep status to show the quality of your data in a clearer way and help you improve your sleep quality."
              "\n"
              "\n"
          " 4.2 Public information"
              "\n"
          "4.2.1 Public information is any information that you share publicly and that anyone can view or access during the use and non-use of the SMART-TIME PRO Service, such as the content of third parties where you have taken screenshots of the relevant pages of the SMART-TIME PRO App."
              "\n"
              "\n"
              "4.3. Sports permissions"
              "\n"
              "\n"
              " 4.3.1 Using the sports module requires you to apply for location permissions and background location permissions to assist sports functions"
              "\n"
              "\n"
              " 5. Management of user information"
              "\n"
              "\n"
              "For operations related to user information management, in order to ensure safety, you need to contact us directly via the email smartwatch@yeah.net . After receiving the information, our staff will contact you by email or phone, and after proving your identity , We will process your request according to the actual situation."
              "\n"
              "\n"
              "5.1 Access and update your information: You can use the app provided by SMART-TIME PRO to log in, query, manage (alter, delete) basic business information (basic information) submitted when using the SMART-TIME PRO services."
              "\n"
              "\n"
              "5.2 Data portability: You have the right to request a copy of your information and request your information in a structured electronic format."
              "\n"
              "\n"
              " 5.3 Delete your information: You can request to remove user information from us in the following cases:"
              "\n"
              "\n"
              "5.3.1 If we process user information in violation of laws and regulations;"
              "\n"
              "\n"
              "5.3.2 If we collect and use your user information without your express consent;"
              "\n"
              "\n"
              "5.3.3 If we process personal information, we commit a serious breach of our agreement with you."
              "\n"
              "\n"
              "5.3.4 If you explicitly want to deactivate the SMART-TIME PRO service"
              "\n"
              "\n"
              "5.3.5 You can find the  option in the app's settings, through which you can directly delete all information about you. Please note that we cannot restore your information after you delete it. If you need to use our product again, you can choose to use it in a login-free mode (all data is only stored locally), or after re-registering our App use."
              "\n"
              "\n"
          " 6. Security of user information"
              "\n"
              " 6.1 SMART-TIME PRO takes your information security very seriously. We strive to protect your user information with reasonable physical, electronic, and administrative security measures. Protect stoic access, public disclosure, use, modification, corruption, or loss of user information. We use encryption to improve the security of user information, we use trusted protection mechanisms to protect users' information from malicious attacks, we deploy access controls to try to ensure that only authorized personnel has rights to access user information, and we conduct security and privacy training courses, to increase employee awareness of the importance of protecting user information."
              "\n"
              "\n"
              " 6.2 We will take reasonable and feasible measures to avoid collecting irrelevant user information. We will only retain your user information for as long as necessary to achieve the purpose stated in the cost policy, unless an extension of the retention period is required or permitted by law. After the above user information is retained, we will delete or anonymize your personal information."
              "\n"
              "\n"
              " 6.3 Please use a complex password to assist us in keeping your account secure. We will do our best to ensure the security of any information you send us, ensuring that your information is not lost, misused and altered by security measures such as encrypting user passwords. If our physical, technical or administrative protection facilities are damaged, resulting in unauthorized access, public disclosure, alteration or destruction of information, resulting in damage to your legitimate rights and interests, we will be liable accordingly."
              "\n"
              "\n"
              " 6.4 In the event of an unfortunate user information security incident (leakage, loss, etc.), we will promptly inform you in accordance with the requirements of laws and regulations: the basic circumstances and possible impact of a security incident, the actions we have taken or will take, recommendations for autonomous prevention and mitigate risk, your remedies, etc. We will promptly inform you of the incident-related situation by email, letter, telephone, push notification and so on, while it is difficult to inform the user information subject, we will take a reasonable and effective way to issue an announcement."
              "\n"
              "\n"
              "6.5 Meanwhile, we will also report the handling of user information security incidents in accordance with regulatory requirements."
              "\n"
              "\n"
              "  6.6 To meet the requirements of laws and regulations indifferent countries and regions, after you select a designated region, your personal data will be completely stored in that region. Please note that the data between different regions is completely independent."
              "\n"
              "\n"
              "6.7 In the event that the SMART-TIME PRO products and services cease to operate, we will take reasonable measures to protect the security of your user information, including timely stopping activities to continue to collect user information; notice of suspension of operations will be notified to users in the form of one-on-one service or announcements; the personal information held will be deleted or anonymized."
              "\n"
              "\n"
              "6.8 We will inform you again and obtain your express consent before using the user information beyond its stated purpose in collecting the user information or beyond a range that has a direct or reasonable association."
              "\n"
              "\n"
          " 6.9 SMART-TIME PRO's product service side is used by China Ali Cloud Company server, its official website access address is: https://www.aliyun.com/. The information and materials related to you in the SMART-TIME PRO's App products are only stored on Ali Cloud servers, and SMART-TIME PRO does not store relevant materials locally."
              "\n"
              "\n"
          " 6.10 Time frame for user data saving: As long as your account is active, we will retain your account information while your motion data, and our terminal devices support displaying your data for the previous 6 months from the current time."
              "\n"
              "\n"
          "7. Our policy towards children"
              "\n"
              "\n"
          "We comply with the requirements of the EU General Data Protection Regulation  and the Children's Online Privacy Protection Act . SMART-TIME PRO services are available for people at least 16 years of age or above. If you are the guardian of a child under the age of 16, you acknowledge and warrant your consent and consent to the use of the Platform and to this Privacy Policy."
              "\n"
              "\n"
          "8. Claims about app permission usage"
              "\n"
              "\n"
          "SMART-TIME PRO's App uses Bluetooth (BLE) to communicate with the device and is a In daily use, SMART-TIME PRO's App will apply to users for phone reading and SMART-TIME PRO reading or receiving permissions. The user is reminded to allow these permissions before using them. These permissions are limited to the implementation of information push function, the phone received by the call and SMS messages and content, pushed to the smart watch side, so as to remind users with new messages for users to view. SMART-TIME PRO solemnly affirms that we will not upload or process any phone and text message content, and will never abuse these permissions, apply for these permissions only to implement the message push function. You can reject these permissions, only affect the message push function. Generally for functional integrity and user experience perspective, SMART-TIME PRO recommends that users agree to these permissions."
              "\n"
              "\n"
          " 9. The Updating of Privacy Policy"
              "\n"
              "\n"
          " 9.1 Our privacy policy is likely to be revised."
              "\n"
              "\n"
          " 9.2 We will not limit your rights under this Privacy Policy without your express consent."
              "\n"
              "\n"
          " 9.3 Significant changes within the meaning of this policy include, but are not limited to:"
              "\n"
              "\n"
          " 9.3.1 There have been significant changes in our service model. Such as the purpose of processing user information, the type of user information processed, the use of user information, etc."
              "\n"
              "\n"
              "9.3.2 We have significant changes in control, organizational structure, etc. Such as business adjustment,",
            style:TextStyle(fontWeight: FontWeight.bold) ,),
        ),
      ),
    );
  }
}
